version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: finesService-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: finesService
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: fines-backend
    restart: always
    ports:
       - "8084:8084"  # pour CitizenService
       - "8085:8085"  # pour FinesService
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://db:3306/finesService?useSSL=false&allowPublicKeyRetrieval=true
      DB_USER: root
      DB_PASSWORD: root123
volumes:
  mysql_data:
